export const IMAGES = {
  LOGO: "/images/logo.png",
  BLOCKCHIAN_ICON: "/images/signin/blockchain.png",
  RIGHT_ARROW: "/images/signin/right-arrow.png",
  DASHBOARD: "/images/sidebar/dashboard.png",
  GROUPS: "/images/sidebar/groups.png",
  SETTINGS: "/images/sidebar/settings.png",
  NOTIFICATION: "/images/header/notifications_unread.png",
  CARET_DOWN: "/images/header/caret-down.png",
  SEARCH: "/images/header/search.png",
  AVATAR: "/images/header/avatar.png",
  CELEBRATE_FILL: "/images/dashboard/celebrate-fill.png",
  CARD_BACKGROUND: "/images/dashboard/card-background.png",
  SPARKLE: "/images/dashboard/sparkle.png",
  SPARKLE_WHITE: "/images/dashboard/sparkle-white.png",
  COPY_ICON: "/images/header/copy.png",
  HELP_ICON: "/images/header/help-icon.png",
  LOGOUT_ICON: "/images/header/logout.png",
  PROFILE_ICON: "/images/header/avatar-1.png",
  BACK_ARROW: "/images/arrow_back.png",
  CALENDAR_ICON: "/images/form/calendar-icon.png",
};
